### PR TITLE
screen: Don't crash when first tab doesn't exist

### LINKED ISSUE #1645: Crash when attaching when only "Tab 2" exists
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: 0.31.1
`stty size`: 64 252
`uname -av` or `ver`(Windows): Linux ********** 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

**Further information**

1. Run zellij.
2. Create a new tab, then close the first tab. There should be only 1 tab, called `Tab #2`.
3. Detach ungracefully by force-closing the terminal window
4. Launch a new terminal window, attempt to attach
5. Zellij crashes:

```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │     1. ipc_server: AttachClient
  │     2. screen_thread: AddClient
  │
  ├─▶ At /home/lucretiel/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.1/src/screen.rs:719:14
  ╰─▶ called `Option::unwrap()` on a `None` value
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
         7: <unknown>
         8: <unknown>
         9: <unknown>
        10: <unknown>
        11: <unknown>
        12: <unknown>
        13: <unknown>
        14: <unknown>
        15: start_thread
        16: clone

  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

In case it matters, I'm running zellij on a server that I access via ssh from Windows Terminal on a Windows machine. The server itself is real hardware, not a VM.

### PR DESCRIPTION
**Pull request by har7an**
while trying to attach a new client. Instead, check whether the first
tab does exist and if not, take the first tab index from the tabs
present in the session. If no tabs exist, panic with a better error
message.

Fixes #1645

### CODE REVIEW

**Comment by har7an** [comment]
Curiously, when attaching now the status bar believes we are in tab mode when we are in fact not. Investigating...

Also I think this deserves a test to prevent regressions, but where/how would I test that? Is this a candidate for an e2e test?

**Comment by imsnif** [comment]
> Curiously, when attaching now the status bar believes we are in tab mode when we are in fact not...

Is this something introduced by this fix?

**Comment by har7an** [comment]
> Is this something introduced by this fix?

Hard to say, previously it would just crash and die when there wasn't a first tab. I guess you could say so.

**Comment by imsnif** [comment]
Cool, happy you're looking into this.

About tests, maybe try here: https://github.com/zellij-org/zellij/blob/main/zellij-server/src/unit/screen_tests.rs

**Comment by har7an** [comment]
@imsnif It seems the `mode_info` sent to the plugins has `mode` set to `Tab`. It happens in `server/src/screen.rs` around line 644, where the Screen queries itself for the `ModeInfo` of the client that is attached. I would expect that to turn up empty and fallback to the default, but it finds one with `ModeInfo.mode` set to `Tab`.

Do you have an idea how that can be? Are the client IDs shared in a session?

**Comment by har7an** [comment]
Been fiddling with it but I cannot make out the reason for this behavior. Maybe it's because something in the code sees that the tab index is different from what it expects, and then just thinks "Oh we switched to a new tab (as in: We made a new tab), so we are in tab mode now"? Other than that I'm out of ideas for now.

Or maybe zellij starts out with the client being in "Tab" mode, sends that to the plugins, immediately updates that to be "Normal" mode and for some reason that doesn't propagate to the plugins anymore? Just guessing...

FYI: I'll be out of town until Tuesday, so if someone else wants to pick this up in the meantime that's fine by me.

File: zellij-server/src/screen.rs [hunk 1]
```diff
@@ -702,21 +702,29 @@ impl Screen {
     }
 
     pub fn add_client(&mut self, client_id: ClientId) {
-        let mut tab_index = 0;
```
Comment (tlinford) [inline zellij-server/src/screen.rs:705]:
```suggestion
let mut tab_index = *self.tabs.keys().next().expect("no tabs found");
```

I think this is maybe easier than changing the logic of the ifs below?

File: zellij-server/src/screen.rs [hunk 2]
```diff
@@ -702,21 +702,29 @@ impl Screen {
...
+            panic!("Can't find a valid tab to attach client to!");
+        };
+
         self.active_tab_indices.insert(client_id, tab_index);
         self.connected_clients.borrow_mut().insert(client_id);
         self.tab_history.insert(client_id, tab_history);
         self.tabs
             .get_mut(&tab_index)
-            .unwrap()
+            .unwrap_or_else(|| panic!("Failed to attach client to tab with index {tab_index}"))
```
Comment (tlinford) [inline zellij-server/src/screen.rs:727]: couldn't this just be an expect?

**Comment by har7an** [comment]
On Wed, 2022-08-10 at 09:41 -0700, Thomas Linford wrote:
> @tlinford commented on this pull request.
> 
> 
> 
> >          self.active_tab_indices.insert(client_id, tab_index);
>          self.connected_clients.borrow_mut().insert(client_id);
>          self.tab_history.insert(client_id, tab_history);
>          self.tabs
>              .get_mut(&tab_index)
> -            .unwrap()
> +            .unwrap_or_else(|| panic!("Failed to attach client to tab with
> index {tab_index}"))
> 
> couldn't this just be an expect?

Originally it was, but that makes clippy unhappy, because `expect()` takes a
`&str`, so you end up doing `expect(format!(...))`. Apparently that's bad. :)

>

**Comment by har7an** [comment]
I wouldn't call it easier, because IMO it makes the code less readable to the
extent that there are two places where the `tab_index` is handled separately.
Also this gets rid of the `mut`, since I'm assigning the whole thing in one go.
The idea of making things `mut` and then assigning them inside an `if` branch
just looks/feels too much like C to me, and I don't like that.

But you've been a project member for longer, so if you prefer this I'll accept
it, of course.

**Comment by tlinford** [comment]
> Originally it was, but that makes clippy unhappy, because `expect()` takes a `&str`, so you end up doing `expect(format!(...))`. Apparently that's bad. :)

ha, I see.

> I wouldn't call it easier, because IMO it makes the code less readable to the
extent that there are two places where the `tab_index` is handled separately.
Also this gets rid of the `mut`, since I'm assigning the whole thing in one go.
The idea of making things `mut` and then assigning them inside an `if` branch
just looks/feels too much like C to me, and I don't like that.

I can get on board with that reasoning!

The one thing I still don't get though is the special casing for tab id 0: ` else if self.tabs.contains_key(&0) `? wouldn't that be covered by `else if let Some(tab_index) = self.tabs.keys().next()`?
