### PR TITLE
Fix Tab (Sync) suffix

### LINKED ISSUE #409: The "Sync" suffix doesn't appear for named tabs
To reproduce:
1. `ctrl-p` + `s` - get into sync mode
2. `ctrl-t` + `r` - rename tab
3. enter a new name
4. see that the "sync" part was deleted

Also:
1. `ctrl-t` + `r` - rename tab
2. `ctrl-p` + `s` - sync mode
3. the "sync" suffix does not appear in the tab name

### PR DESCRIPTION
**Pull request by dantepippi**
Closes #409

### CODE REVIEW

File: default-plugins/tab-bar/src/tab.rs [hunk 1]
```diff
@@ -47,14 +47,15 @@ pub fn tab_style(
...
+        false => "",
     };
-    let tab_text = if text.is_empty() {
-        format!("Tab #{}{}", position + 1, sync_text)
+    let mut tab_text = if text.is_empty() {
+        format!("Tab #{}", position + 1)
     } else {
         text
     };
+    tab_text.push_str(sync_text);
```
Comment (TheLostLambda) [inline default-plugins/tab-bar/src/tab.rs:58]: As a matter of style and efficiency, I'd probably just write:

```rust
if is_sync_panes_active {
    tab_text.push_str(" (Sync)");
}
```

But I'm happy to merge either!

**Review by TheLostLambda — APPROVED** [review]

File: default-plugins/tab-bar/src/tab.rs (hunk 1 above)
Comment (dantepippi) [reply default-plugins/tab-bar/src/tab.rs]: Done.

**Comment by TheLostLambda** [comment]
Thanks for this! Merged!
