### PR TITLE
fix(web-client): use base URL when switching sessions

### LINKED ISSUE #4980: Web client: session switch ignores base_url behind reverse proxy
When switching sessions via the session manager, the web client redirects to `/{session_name}` instead of `{base_url}/{session_name}`, ignoring the configured `base_url`.

**Steps to reproduce:**
1. Configure `base_url = "/zellij/"` in `web_client` config
2. Set up a reverse proxy (e.g. Caddy `handle_path /zellij*`)
3. Connect to the web client, create multiple sessions
4. Switch sessions using the session manager

**Expected:** Browser navigates to `/zellij/my-session`
**Actual:** Browser navigates to `/my-session` (404)

**Root cause:** `websockets.js` line 244 hardcodes `window.location.pathname = \`/\${new_session_name}\`` without using the base URL.

### PR DESCRIPTION
**Pull request by TMYTiMidlY**
## Summary

Fixes #4980

When switching sessions via the session manager, the web client redirects to `/{session_name}`, ignoring the configured `base_url`. This breaks all reverse proxy setups that serve zellij under a subpath.

## Changes

Use `getBaseUrl()` to construct the redirect URL in `websockets.js`, consistent with how `auth.js` and `connection.js` already handle the base URL.

## Testing

Tested with Caddy reverse proxy (`handle_path /zellij-dev*` → `localhost:8084`) and `base_url = "/zellij-dev/"`. Session switching now correctly navigates to `/zellij-dev/{session_name}`.

### CODE REVIEW

File: zellij-client/assets/websockets.js [hunk 1]
```diff
@@ -241,7 +241,8 @@ function startWsControl(wsControl, term, fitAddon, ownWebClientId, userConfig) {
             }
         } else if (msg.type === "SwitchedSession") {
             const { new_session_name } = msg;
-            window.location.pathname = `/${new_session_name}`;
+            const baseUrl = getBaseUrl();
+            window.location.href = `${baseUrl}/${new_session_name}`;
```
Comment (tlinford) [inline zellij-client/assets/websockets.js]: just a small thing, should use `${encodeURIComponent(new_session_name)`.
href and pathname behave a bit differently and we could have problems if the session name contains special characters

Comment (TMYTiMidlY) [reply zellij-client/assets/websockets.js]: Done, thanks for catching this!

Comment (tlinford) [reply zellij-client/assets/websockets.js]: Merged, thanks for the fix!
