### PR TITLE
fix(utils): validate session name

### LINKED ISSUE #2591: Long session name hangs zellij
`zellij --session reallyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy` works. 
`zellij --session reallyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy` is hanging the program.

The latter one is 37 characters long

### PR DESCRIPTION
**Pull request by deepsghimire**
This PR fixes #2591

### CODE REVIEW

File: zellij-utils/src/cli.rs [hunk 1]
```diff
@@ -9,6 +9,26 @@ use serde::{Deserialize, Serialize};
...
 
+fn validate_session(name: &str) -> Result<String, String> {
+    #[cfg(unix)]
+    {
+        let mut socket_path = crate::consts::ZELLIJ_SOCK_DIR.clone();
+        let available_length = 108_usize
+            .saturating_sub(socket_path.as_os_str().len())
+            .saturating_sub(1);
+        socket_path.push(name);
+        if socket_path.as_os_str().len() >= 108 {
```
Comment (silicakes) [inline zellij-utils/src/cli.rs:20]: Consider extracting it into some constant just because it's being reused here and under `available_length`

Comment (jaeheonji) [reply zellij-utils/src/cli.rs:20]: I think it is good idea. @deepsghimire could you please update this? Or if you're busy can I work on this?

Comment (deepsghimire) [reply zellij-utils/src/cli.rs:20]: Hi, yes you can work on this.
